name: firecracker
version: git
summary: Secure and fast microVMs.
description:| 
Secure and fast microVMs for serverless computing.
  
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  
parts:
  firecracker:
    plugin: rust
    source: .

apps:
  firecracker:
    command: firecracker
    plugs:
      - home
      - removable-media
