name: firecracker
base: core18 # the base snap is the execution environment for this snap
version: 0.15.0
summary: Secure and fast microVMs.
description:| 
Secure and fast microVMs for serverless computing.
  
grade: stable
confinement: strict

parts:
  firecracker:
    plugin: rust
    source: .

apps:
  firecracker:
    command: firecracker
    plugs:
      - home
      - removable-media
